-- MySQL Script generated by BonesFox64
-- Fri Jul 05 11:13:00 2024
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema prueba
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `prueba` DEFAULT CHARACTER SET utf8 ;
USE `prueba` ;

-- -----------------------------------------------------
-- Table `prueba`.`user`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `prueba`.`user` (
  `id_user` VARCHAR(255) NOT NULL,
  `username` VARCHAR(255) NOT NULL UNIQUE,
  `password` VARCHAR(255) NOT NULL,
  `user_email` VARCHAR(255) NOT NULL,
  PRIMARY KEY (`id_user`))
ENGINE = InnoDB;

-- -----------------------------------------------------
-- Table `prueba`.`categoria`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `prueba`.`categoria` (
  `id_categoria` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  `nombre_categoria` TEXT NOT NULL,
  PRIMARY KEY (`id_categoria`))
ENGINE = InnoDB;

-- -----------------------------------------------------
-- Table `prueba`.`producto`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `prueba`.`producto` (
  `id_producto` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  `nombre_producto` TEXT NOT NULL,
  `categoria` BIGINT UNSIGNED NOT NULL,
  PRIMARY KEY (`id_producto`),
  CONSTRAINT `fk_producto_categoria`
    FOREIGN KEY (`categoria`)
    REFERENCES `prueba`.`categoria` (`id_categoria`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

-- -----------------------------------------------------
-- Table `prueba`.`cliente`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `prueba`.`cliente` (
  `id_cliente` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  `nombre_cliente` TEXT NOT NULL,
  `num_cliente` TEXT NOT NULL,
  PRIMARY KEY (`id_cliente`))
ENGINE = InnoDB;

-- -----------------------------------------------------
-- Table `prueba`.`venta`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `prueba`.`venta` (
  `id_venta` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  `cliente` BIGINT UNSIGNED NOT NULL,
  `folio` TEXT NOT NULL,
  `fecha` DATETIME NOT NULL,
  `total` INT UNSIGNED NOT NULL,
  PRIMARY KEY (`id_venta`),
  CONSTRAINT `fk_venta_cliente`
    FOREIGN KEY (`cliente`)
    REFERENCES `prueba`.`cliente` (`id_cliente`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

-- -----------------------------------------------------
-- Table `prueba`.`venta_producto`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `prueba`.`venta_producto` (
  `id_venta` BIGINT UNSIGNED NOT NULL,
  `id_producto` BIGINT UNSIGNED NOT NULL,
  `cantidad` INT UNSIGNED NOT NULL,
  `precio` INT UNSIGNED NOT NULL,
  CONSTRAINT `fk_venta_venta_producto`
    FOREIGN KEY (`id_venta`)
    REFERENCES `prueba`.`venta` (`id_venta`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_producto_venta_producto`
    FOREIGN KEY (`id_producto`)
    REFERENCES `prueba`.`producto` (`id_producto`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

INSERT INTO `categoria` (`nombre_categoria`) VALUES ('Electrónicos');
INSERT INTO `categoria` (`nombre_categoria`) VALUES ('Herramienta');
INSERT INTO `categoria` (`nombre_categoria`) VALUES ('Abarrotes');
INSERT INTO `categoria` (`nombre_categoria`) VALUES ('Dulcería');

INSERT INTO `producto` (`nombre_producto`, `categoria`) VALUES ('Martillo', '2');
INSERT INTO `producto` (`nombre_producto`, `categoria`) VALUES ('Destornillador', '2');
INSERT INTO `producto` (`nombre_producto`, `categoria`) VALUES ('Laptop', '1');
INSERT INTO `producto` (`nombre_producto`, `categoria`) VALUES ('Tablet', '1');
INSERT INTO `producto` (`nombre_producto`, `categoria`) VALUES ('Helado', '3');
INSERT INTO `producto` (`nombre_producto`, `categoria`) VALUES ('Papas', '4');
INSERT INTO `producto` (`nombre_producto`, `categoria`) VALUES ('Caramelos', '4');

INSERT INTO `cliente` (`nombre_cliente`, `num_cliente`) VALUES ('Juan Pérez', '123456789');
INSERT INTO `cliente` (`nombre_cliente`, `num_cliente`) VALUES ('María Rodríguez', '987654321');
INSERT INTO `cliente` (`nombre_cliente`, `num_cliente`) VALUES ('Pedro Gómez', '123456780');

INSERT INTO `venta` (`cliente`, `folio`, `fecha`, `total`) VALUES (1, 'VENTA-001', '2024-04-05 10:30:00', 2050);
INSERT INTO `venta` (`cliente`, `folio`, `fecha`, `total`) VALUES (2, 'VENTA-002', '2024-04-06 15:00:00', 700);
INSERT INTO `venta` (`cliente`, `folio`, `fecha`, `total`) VALUES (3, 'VENTA-003', '2024-04-07 11:30:00', 190);

INSERT INTO `venta_producto` (`id_venta`, `id_producto`, `cantidad`, `precio`) VALUES 
(1, 3, 2, 1000), -- 2 laptops a $1000 cada una en la venta 1
(1, 6, 1, 50);  -- 1 paquete de papas en la venta 1
(1, 2, 1, 80);  -- 1 destornillador en la venta 1
(1, 1, 1, 120);  -- 1 destornillador en la venta 1

INSERT INTO `venta_producto` (`id_venta`, `id_producto`, `cantidad`, `precio`) VALUES 
(2, 4, 1, 500),  -- 1 tablet en la venta 2
(2, 6, 2, 100);  -- 2 paquetes de papas en la venta 2
INSERT INTO `venta_producto` (`id_venta`, `id_producto`, `cantidad`, `precio`) VALUES 
(3, 1, 3, 30),   -- 3 martillos en la venta 3
(3, 7, 5, 20);   -- 5 caramelos en la venta 3

SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
